# Generated by Django 3.1.3 on 2020-12-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=40, verbose_name='Email Address')),
                ('message', models.TextField(verbose_name='Message')),
                ('staff', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Staff user working on the request')),
                ('is_new', models.BooleanField(default=True, verbose_name='Is it a new request?')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Is the user registered?')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is it being processed?')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is it finished?')),
                ('is_informed', models.BooleanField(default=False, verbose_name='Is user informed?')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of request')),
                ('finished_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of finished request')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ('is_new', 'request_date'),
            },
        ),
    ]
