# Generated by Django 3.1.3 on 2020-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, verbose_name='Gender')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('city', models.CharField(max_length=20, verbose_name='City, State')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('secret_question', models.CharField(choices=[('1', 'What was your childhood nickname?'), ('2', 'What was the name of your second pet?'), ('3', 'What street did you live on in third grade?')], max_length=255, verbose_name='Secret Question')),
                ('secret_answer', models.CharField(max_length=20, verbose_name='Secret Answer')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
